### ISSUE TITLE
How to add scss support?

### ISSUE THREAD

**Issue by Farrukhameen** [Ballpin/mern-starter2#1]
Thank you for such a comprehensive starter. This is my favorite mern boilerplate on github. but I need sass/scss support for my project. How can I add that?

**Comment by Ballpin** [comment]
Hi Farrukhameen,

Thanks, but most of the credits should go to the developers behind [React, Universally](https://github.com/ctrlplusb/react-universally) and [mern-starter](https://github.com/Hashnode/mern-starter). I just combined those two get a MERN boilerplate. Both of them had stuff i liked :-)

In order to add SCSS you need to add a few lines of code to Webpack configuration. You can find the configuration in  "mern-starter2/internal/webpack/configFactory.js" in webpackConfig variable.
Check [SASS Loader](https://github.com/webpack-contrib/sass-loader) for sample configuration.

I would however recommend using [Styled Components](https://www.styled-components.com/docs/basics). You get encapsulated CSS code just like Angular 2 has. You code the CSS same way you do with with SCSS to. Its a bit of a learning curve, but its really cool once you get a hang of it.

**Comment by Farrukhameen** [comment]
Thank you it helped. I will study styled components for next project.
